name: lazygit
base: core20
version: '0.33'
summary: simple terminal UI for git commands
description: |
  A simple terminal UI for git commands, written in Go with the gocui library.

grade: stable
confinement: strict

parts:
  lazygit:
    plugin: go
    source: git://github.com/jesseduffield/lazygit.git
    source-tag: v0.33
    stage-packages:
    - git
    organize:
      lazygit: bin/

apps:
  lazygit:
    command: bin/lazygit
